# Site settings
title: atzman music
email: atzmanmusic@chello.at

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasparkety.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
timezone: Europe/Vienna
encoding: utf-8

defaults:
 -
   scope:
     path: ""
   values:
     layout: "default"


collections:
  jobs:
    output: true
  articles:
      output: true
  tutorials:
      output: true

sass:
  sass_dir: css

plugins:
  - jekyll-redirect-from

# Google Analytics Cide
google_analytics: 
