# Site settings
title: atzman music
email: atzmanmusic@chello.at

baseurl: "" # the subpath of your site, e.g. /blog/
url: "atzman.github.io"


# Build settings
markdown: kramdown
timezone: Europe/Vienna
encoding: utf-8

defaults:
 -
   scope:
     path: ""
   values:
     layout: "default"

sass:
  sass_dir: css

plugins:
  - jekyll-redirect-from
